#if which swiftlint >/dev/null; then
#swiftlint
#else
#echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
#E
#fi


disabled_rules:
    - identifier_name
    - trailing_whitespace

opt_in_rules:
    - empty_count
    - empty_string
    
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
    
function_body_length:
    warning: 300
    error: 500
    
line_length:
    warning: 200
    error: 300
    ignores_urls: true
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

